/*
API Образов облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps-image

import (
	"encoding/json"
)

// ImageGetCalculationResponse struct for ImageGetCalculationResponse
type ImageGetCalculationResponse struct {
	PriceCalculationInfo *ImagePriceCalculationInfo `json:"price_calculation_info,omitempty"`
	Error *ImageGetCalculationResponseError `json:"error,omitempty"`
}

// NewImageGetCalculationResponse instantiates a new ImageGetCalculationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageGetCalculationResponse() *ImageGetCalculationResponse {
	this := ImageGetCalculationResponse{}
	return &this
}

// NewImageGetCalculationResponseWithDefaults instantiates a new ImageGetCalculationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageGetCalculationResponseWithDefaults() *ImageGetCalculationResponse {
	this := ImageGetCalculationResponse{}
	return &this
}

// GetPriceCalculationInfo returns the PriceCalculationInfo field value if set, zero value otherwise.
func (o *ImageGetCalculationResponse) GetPriceCalculationInfo() ImagePriceCalculationInfo {
	if o == nil || isNil(o.PriceCalculationInfo) {
		var ret ImagePriceCalculationInfo
		return ret
	}
	return *o.PriceCalculationInfo
}

// GetPriceCalculationInfoOk returns a tuple with the PriceCalculationInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageGetCalculationResponse) GetPriceCalculationInfoOk() (*ImagePriceCalculationInfo, bool) {
	if o == nil || isNil(o.PriceCalculationInfo) {
    return nil, false
	}
	return o.PriceCalculationInfo, true
}

// HasPriceCalculationInfo returns a boolean if a field has been set.
func (o *ImageGetCalculationResponse) HasPriceCalculationInfo() bool {
	if o != nil && !isNil(o.PriceCalculationInfo) {
		return true
	}

	return false
}

// SetPriceCalculationInfo gets a reference to the given ImagePriceCalculationInfo and assigns it to the PriceCalculationInfo field.
func (o *ImageGetCalculationResponse) SetPriceCalculationInfo(v ImagePriceCalculationInfo) {
	o.PriceCalculationInfo = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ImageGetCalculationResponse) GetError() ImageGetCalculationResponseError {
	if o == nil || isNil(o.Error) {
		var ret ImageGetCalculationResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageGetCalculationResponse) GetErrorOk() (*ImageGetCalculationResponseError, bool) {
	if o == nil || isNil(o.Error) {
    return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ImageGetCalculationResponse) HasError() bool {
	if o != nil && !isNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given ImageGetCalculationResponseError and assigns it to the Error field.
func (o *ImageGetCalculationResponse) SetError(v ImageGetCalculationResponseError) {
	o.Error = &v
}

func (o ImageGetCalculationResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.PriceCalculationInfo) {
		toSerialize["price_calculation_info"] = o.PriceCalculationInfo
	}
	if !isNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableImageGetCalculationResponse struct {
	value *ImageGetCalculationResponse
	isSet bool
}

func (v NullableImageGetCalculationResponse) Get() *ImageGetCalculationResponse {
	return v.value
}

func (v *NullableImageGetCalculationResponse) Set(val *ImageGetCalculationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableImageGetCalculationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableImageGetCalculationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageGetCalculationResponse(val *ImageGetCalculationResponse) *NullableImageGetCalculationResponse {
	return &NullableImageGetCalculationResponse{value: val, isSet: true}
}

func (v NullableImageGetCalculationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageGetCalculationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


