/*
API Образов облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVpsImage

import (
	"encoding/json"
)

// checks if the ImageGetListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageGetListResponse{}

// ImageGetListResponse struct for ImageGetListResponse
type ImageGetListResponse struct {
	Images []ImageImage `json:"images,omitempty"`
	TotalCount *int32 `json:"total_count,omitempty"`
}

// NewImageGetListResponse instantiates a new ImageGetListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageGetListResponse() *ImageGetListResponse {
	this := ImageGetListResponse{}
	return &this
}

// NewImageGetListResponseWithDefaults instantiates a new ImageGetListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageGetListResponseWithDefaults() *ImageGetListResponse {
	this := ImageGetListResponse{}
	return &this
}

// GetImages returns the Images field value if set, zero value otherwise.
func (o *ImageGetListResponse) GetImages() []ImageImage {
	if o == nil || IsNil(o.Images) {
		var ret []ImageImage
		return ret
	}
	return o.Images
}

// GetImagesOk returns a tuple with the Images field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageGetListResponse) GetImagesOk() ([]ImageImage, bool) {
	if o == nil || IsNil(o.Images) {
		return nil, false
	}
	return o.Images, true
}

// HasImages returns a boolean if a field has been set.
func (o *ImageGetListResponse) HasImages() bool {
	if o != nil && !IsNil(o.Images) {
		return true
	}

	return false
}

// SetImages gets a reference to the given []ImageImage and assigns it to the Images field.
func (o *ImageGetListResponse) SetImages(v []ImageImage) {
	o.Images = v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *ImageGetListResponse) GetTotalCount() int32 {
	if o == nil || IsNil(o.TotalCount) {
		var ret int32
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageGetListResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *ImageGetListResponse) HasTotalCount() bool {
	if o != nil && !IsNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *ImageGetListResponse) SetTotalCount(v int32) {
	o.TotalCount = &v
}

func (o ImageGetListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageGetListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Images) {
		toSerialize["images"] = o.Images
	}
	if !IsNil(o.TotalCount) {
		toSerialize["total_count"] = o.TotalCount
	}
	return toSerialize, nil
}

type NullableImageGetListResponse struct {
	value *ImageGetListResponse
	isSet bool
}

func (v NullableImageGetListResponse) Get() *ImageGetListResponse {
	return v.value
}

func (v *NullableImageGetListResponse) Set(val *ImageGetListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableImageGetListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableImageGetListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageGetListResponse(val *ImageGetListResponse) *NullableImageGetListResponse {
	return &NullableImageGetListResponse{value: val, isSet: true}
}

func (v NullableImageGetListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageGetListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


