/*
API Образов облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVpsImage

import (
	"encoding/json"
)

// checks if the ImageCreateImageResponseErrorRegionMismatchError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageCreateImageResponseErrorRegionMismatchError{}

// ImageCreateImageResponseErrorRegionMismatchError struct for ImageCreateImageResponseErrorRegionMismatchError
type ImageCreateImageResponseErrorRegionMismatchError struct {
	VpsRegion *string `json:"vps_region,omitempty"`
	RequestedRegion *string `json:"requested_region,omitempty"`
}

// NewImageCreateImageResponseErrorRegionMismatchError instantiates a new ImageCreateImageResponseErrorRegionMismatchError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageCreateImageResponseErrorRegionMismatchError() *ImageCreateImageResponseErrorRegionMismatchError {
	this := ImageCreateImageResponseErrorRegionMismatchError{}
	return &this
}

// NewImageCreateImageResponseErrorRegionMismatchErrorWithDefaults instantiates a new ImageCreateImageResponseErrorRegionMismatchError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageCreateImageResponseErrorRegionMismatchErrorWithDefaults() *ImageCreateImageResponseErrorRegionMismatchError {
	this := ImageCreateImageResponseErrorRegionMismatchError{}
	return &this
}

// GetVpsRegion returns the VpsRegion field value if set, zero value otherwise.
func (o *ImageCreateImageResponseErrorRegionMismatchError) GetVpsRegion() string {
	if o == nil || IsNil(o.VpsRegion) {
		var ret string
		return ret
	}
	return *o.VpsRegion
}

// GetVpsRegionOk returns a tuple with the VpsRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageCreateImageResponseErrorRegionMismatchError) GetVpsRegionOk() (*string, bool) {
	if o == nil || IsNil(o.VpsRegion) {
		return nil, false
	}
	return o.VpsRegion, true
}

// HasVpsRegion returns a boolean if a field has been set.
func (o *ImageCreateImageResponseErrorRegionMismatchError) HasVpsRegion() bool {
	if o != nil && !IsNil(o.VpsRegion) {
		return true
	}

	return false
}

// SetVpsRegion gets a reference to the given string and assigns it to the VpsRegion field.
func (o *ImageCreateImageResponseErrorRegionMismatchError) SetVpsRegion(v string) {
	o.VpsRegion = &v
}

// GetRequestedRegion returns the RequestedRegion field value if set, zero value otherwise.
func (o *ImageCreateImageResponseErrorRegionMismatchError) GetRequestedRegion() string {
	if o == nil || IsNil(o.RequestedRegion) {
		var ret string
		return ret
	}
	return *o.RequestedRegion
}

// GetRequestedRegionOk returns a tuple with the RequestedRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageCreateImageResponseErrorRegionMismatchError) GetRequestedRegionOk() (*string, bool) {
	if o == nil || IsNil(o.RequestedRegion) {
		return nil, false
	}
	return o.RequestedRegion, true
}

// HasRequestedRegion returns a boolean if a field has been set.
func (o *ImageCreateImageResponseErrorRegionMismatchError) HasRequestedRegion() bool {
	if o != nil && !IsNil(o.RequestedRegion) {
		return true
	}

	return false
}

// SetRequestedRegion gets a reference to the given string and assigns it to the RequestedRegion field.
func (o *ImageCreateImageResponseErrorRegionMismatchError) SetRequestedRegion(v string) {
	o.RequestedRegion = &v
}

func (o ImageCreateImageResponseErrorRegionMismatchError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageCreateImageResponseErrorRegionMismatchError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VpsRegion) {
		toSerialize["vps_region"] = o.VpsRegion
	}
	if !IsNil(o.RequestedRegion) {
		toSerialize["requested_region"] = o.RequestedRegion
	}
	return toSerialize, nil
}

type NullableImageCreateImageResponseErrorRegionMismatchError struct {
	value *ImageCreateImageResponseErrorRegionMismatchError
	isSet bool
}

func (v NullableImageCreateImageResponseErrorRegionMismatchError) Get() *ImageCreateImageResponseErrorRegionMismatchError {
	return v.value
}

func (v *NullableImageCreateImageResponseErrorRegionMismatchError) Set(val *ImageCreateImageResponseErrorRegionMismatchError) {
	v.value = val
	v.isSet = true
}

func (v NullableImageCreateImageResponseErrorRegionMismatchError) IsSet() bool {
	return v.isSet
}

func (v *NullableImageCreateImageResponseErrorRegionMismatchError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageCreateImageResponseErrorRegionMismatchError(val *ImageCreateImageResponseErrorRegionMismatchError) *NullableImageCreateImageResponseErrorRegionMismatchError {
	return &NullableImageCreateImageResponseErrorRegionMismatchError{value: val, isSet: true}
}

func (v NullableImageCreateImageResponseErrorRegionMismatchError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageCreateImageResponseErrorRegionMismatchError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


