/*
API Образов облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps-image

import (
	"encoding/json"
)

// ImageUpdateImageResponseError struct for ImageUpdateImageResponseError
type ImageUpdateImageResponseError struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewImageUpdateImageResponseError instantiates a new ImageUpdateImageResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageUpdateImageResponseError() *ImageUpdateImageResponseError {
	this := ImageUpdateImageResponseError{}
	return &this
}

// NewImageUpdateImageResponseErrorWithDefaults instantiates a new ImageUpdateImageResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageUpdateImageResponseErrorWithDefaults() *ImageUpdateImageResponseError {
	this := ImageUpdateImageResponseError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ImageUpdateImageResponseError) GetCode() string {
	if o == nil || isNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageUpdateImageResponseError) GetCodeOk() (*string, bool) {
	if o == nil || isNil(o.Code) {
    return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ImageUpdateImageResponseError) HasCode() bool {
	if o != nil && !isNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ImageUpdateImageResponseError) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ImageUpdateImageResponseError) GetMessage() string {
	if o == nil || isNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageUpdateImageResponseError) GetMessageOk() (*string, bool) {
	if o == nil || isNil(o.Message) {
    return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ImageUpdateImageResponseError) HasMessage() bool {
	if o != nil && !isNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ImageUpdateImageResponseError) SetMessage(v string) {
	o.Message = &v
}

func (o ImageUpdateImageResponseError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !isNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableImageUpdateImageResponseError struct {
	value *ImageUpdateImageResponseError
	isSet bool
}

func (v NullableImageUpdateImageResponseError) Get() *ImageUpdateImageResponseError {
	return v.value
}

func (v *NullableImageUpdateImageResponseError) Set(val *ImageUpdateImageResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableImageUpdateImageResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableImageUpdateImageResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageUpdateImageResponseError(val *ImageUpdateImageResponseError) *NullableImageUpdateImageResponseError {
	return &NullableImageUpdateImageResponseError{value: val, isSet: true}
}

func (v NullableImageUpdateImageResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageUpdateImageResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


