/*
API Образов облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps-image

import (
	"encoding/json"
)

// ImageImageSourceLinkSource struct for ImageImageSourceLinkSource
type ImageImageSourceLinkSource struct {
	Link *string `json:"link,omitempty"`
}

// NewImageImageSourceLinkSource instantiates a new ImageImageSourceLinkSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageImageSourceLinkSource() *ImageImageSourceLinkSource {
	this := ImageImageSourceLinkSource{}
	return &this
}

// NewImageImageSourceLinkSourceWithDefaults instantiates a new ImageImageSourceLinkSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageImageSourceLinkSourceWithDefaults() *ImageImageSourceLinkSource {
	this := ImageImageSourceLinkSource{}
	return &this
}

// GetLink returns the Link field value if set, zero value otherwise.
func (o *ImageImageSourceLinkSource) GetLink() string {
	if o == nil || isNil(o.Link) {
		var ret string
		return ret
	}
	return *o.Link
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageImageSourceLinkSource) GetLinkOk() (*string, bool) {
	if o == nil || isNil(o.Link) {
    return nil, false
	}
	return o.Link, true
}

// HasLink returns a boolean if a field has been set.
func (o *ImageImageSourceLinkSource) HasLink() bool {
	if o != nil && !isNil(o.Link) {
		return true
	}

	return false
}

// SetLink gets a reference to the given string and assigns it to the Link field.
func (o *ImageImageSourceLinkSource) SetLink(v string) {
	o.Link = &v
}

func (o ImageImageSourceLinkSource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Link) {
		toSerialize["link"] = o.Link
	}
	return json.Marshal(toSerialize)
}

type NullableImageImageSourceLinkSource struct {
	value *ImageImageSourceLinkSource
	isSet bool
}

func (v NullableImageImageSourceLinkSource) Get() *ImageImageSourceLinkSource {
	return v.value
}

func (v *NullableImageImageSourceLinkSource) Set(val *ImageImageSourceLinkSource) {
	v.value = val
	v.isSet = true
}

func (v NullableImageImageSourceLinkSource) IsSet() bool {
	return v.isSet
}

func (v *NullableImageImageSourceLinkSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageImageSourceLinkSource(val *ImageImageSourceLinkSource) *NullableImageImageSourceLinkSource {
	return &NullableImageImageSourceLinkSource{value: val, isSet: true}
}

func (v NullableImageImageSourceLinkSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageImageSourceLinkSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


