/*
API Образов облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVpsImage

import (
	"encoding/json"
)

// checks if the ImageRestoreImageResponseError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageRestoreImageResponseError{}

// ImageRestoreImageResponseError struct for ImageRestoreImageResponseError
type ImageRestoreImageResponseError struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewImageRestoreImageResponseError instantiates a new ImageRestoreImageResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageRestoreImageResponseError() *ImageRestoreImageResponseError {
	this := ImageRestoreImageResponseError{}
	return &this
}

// NewImageRestoreImageResponseErrorWithDefaults instantiates a new ImageRestoreImageResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageRestoreImageResponseErrorWithDefaults() *ImageRestoreImageResponseError {
	this := ImageRestoreImageResponseError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ImageRestoreImageResponseError) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageRestoreImageResponseError) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ImageRestoreImageResponseError) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ImageRestoreImageResponseError) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ImageRestoreImageResponseError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageRestoreImageResponseError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ImageRestoreImageResponseError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ImageRestoreImageResponseError) SetMessage(v string) {
	o.Message = &v
}

func (o ImageRestoreImageResponseError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageRestoreImageResponseError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableImageRestoreImageResponseError struct {
	value *ImageRestoreImageResponseError
	isSet bool
}

func (v NullableImageRestoreImageResponseError) Get() *ImageRestoreImageResponseError {
	return v.value
}

func (v *NullableImageRestoreImageResponseError) Set(val *ImageRestoreImageResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableImageRestoreImageResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableImageRestoreImageResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageRestoreImageResponseError(val *ImageRestoreImageResponseError) *NullableImageRestoreImageResponseError {
	return &NullableImageRestoreImageResponseError{value: val, isSet: true}
}

func (v NullableImageRestoreImageResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageRestoreImageResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


