/*
API Образов облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps-image

import (
	"encoding/json"
)

// ImageGetCalculationResponseError struct for ImageGetCalculationResponseError
type ImageGetCalculationResponseError struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewImageGetCalculationResponseError instantiates a new ImageGetCalculationResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageGetCalculationResponseError() *ImageGetCalculationResponseError {
	this := ImageGetCalculationResponseError{}
	return &this
}

// NewImageGetCalculationResponseErrorWithDefaults instantiates a new ImageGetCalculationResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageGetCalculationResponseErrorWithDefaults() *ImageGetCalculationResponseError {
	this := ImageGetCalculationResponseError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ImageGetCalculationResponseError) GetCode() string {
	if o == nil || isNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageGetCalculationResponseError) GetCodeOk() (*string, bool) {
	if o == nil || isNil(o.Code) {
    return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ImageGetCalculationResponseError) HasCode() bool {
	if o != nil && !isNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ImageGetCalculationResponseError) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ImageGetCalculationResponseError) GetMessage() string {
	if o == nil || isNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageGetCalculationResponseError) GetMessageOk() (*string, bool) {
	if o == nil || isNil(o.Message) {
    return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ImageGetCalculationResponseError) HasMessage() bool {
	if o != nil && !isNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ImageGetCalculationResponseError) SetMessage(v string) {
	o.Message = &v
}

func (o ImageGetCalculationResponseError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !isNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableImageGetCalculationResponseError struct {
	value *ImageGetCalculationResponseError
	isSet bool
}

func (v NullableImageGetCalculationResponseError) Get() *ImageGetCalculationResponseError {
	return v.value
}

func (v *NullableImageGetCalculationResponseError) Set(val *ImageGetCalculationResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableImageGetCalculationResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableImageGetCalculationResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageGetCalculationResponseError(val *ImageGetCalculationResponseError) *NullableImageGetCalculationResponseError {
	return &NullableImageGetCalculationResponseError{value: val, isSet: true}
}

func (v NullableImageGetCalculationResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageGetCalculationResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


