/*
API Образов облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVpsImage

import (
	"encoding/json"
)

// checks if the ImagePriceCalculationInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImagePriceCalculationInfo{}

// ImagePriceCalculationInfo struct for ImagePriceCalculationInfo
type ImagePriceCalculationInfo struct {
	Price *float64 `json:"price,omitempty"`
}

// NewImagePriceCalculationInfo instantiates a new ImagePriceCalculationInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImagePriceCalculationInfo() *ImagePriceCalculationInfo {
	this := ImagePriceCalculationInfo{}
	return &this
}

// NewImagePriceCalculationInfoWithDefaults instantiates a new ImagePriceCalculationInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImagePriceCalculationInfoWithDefaults() *ImagePriceCalculationInfo {
	this := ImagePriceCalculationInfo{}
	return &this
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *ImagePriceCalculationInfo) GetPrice() float64 {
	if o == nil || IsNil(o.Price) {
		var ret float64
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImagePriceCalculationInfo) GetPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *ImagePriceCalculationInfo) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float64 and assigns it to the Price field.
func (o *ImagePriceCalculationInfo) SetPrice(v float64) {
	o.Price = &v
}

func (o ImagePriceCalculationInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImagePriceCalculationInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	return toSerialize, nil
}

type NullableImagePriceCalculationInfo struct {
	value *ImagePriceCalculationInfo
	isSet bool
}

func (v NullableImagePriceCalculationInfo) Get() *ImagePriceCalculationInfo {
	return v.value
}

func (v *NullableImagePriceCalculationInfo) Set(val *ImagePriceCalculationInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableImagePriceCalculationInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableImagePriceCalculationInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImagePriceCalculationInfo(val *ImagePriceCalculationInfo) *NullableImagePriceCalculationInfo {
	return &NullableImagePriceCalculationInfo{value: val, isSet: true}
}

func (v NullableImagePriceCalculationInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImagePriceCalculationInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


