/*
API Образов облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVps-image

import (
	"encoding/json"
)

// ImageUpdateImageResponse struct for ImageUpdateImageResponse
type ImageUpdateImageResponse struct {
	Image *ImageImage `json:"image,omitempty"`
	Error *ImageUpdateImageResponseError `json:"error,omitempty"`
}

// NewImageUpdateImageResponse instantiates a new ImageUpdateImageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageUpdateImageResponse() *ImageUpdateImageResponse {
	this := ImageUpdateImageResponse{}
	return &this
}

// NewImageUpdateImageResponseWithDefaults instantiates a new ImageUpdateImageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageUpdateImageResponseWithDefaults() *ImageUpdateImageResponse {
	this := ImageUpdateImageResponse{}
	return &this
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *ImageUpdateImageResponse) GetImage() ImageImage {
	if o == nil || isNil(o.Image) {
		var ret ImageImage
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageUpdateImageResponse) GetImageOk() (*ImageImage, bool) {
	if o == nil || isNil(o.Image) {
    return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *ImageUpdateImageResponse) HasImage() bool {
	if o != nil && !isNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given ImageImage and assigns it to the Image field.
func (o *ImageUpdateImageResponse) SetImage(v ImageImage) {
	o.Image = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ImageUpdateImageResponse) GetError() ImageUpdateImageResponseError {
	if o == nil || isNil(o.Error) {
		var ret ImageUpdateImageResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageUpdateImageResponse) GetErrorOk() (*ImageUpdateImageResponseError, bool) {
	if o == nil || isNil(o.Error) {
    return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ImageUpdateImageResponse) HasError() bool {
	if o != nil && !isNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given ImageUpdateImageResponseError and assigns it to the Error field.
func (o *ImageUpdateImageResponse) SetError(v ImageUpdateImageResponseError) {
	o.Error = &v
}

func (o ImageUpdateImageResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !isNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableImageUpdateImageResponse struct {
	value *ImageUpdateImageResponse
	isSet bool
}

func (v NullableImageUpdateImageResponse) Get() *ImageUpdateImageResponse {
	return v.value
}

func (v *NullableImageUpdateImageResponse) Set(val *ImageUpdateImageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableImageUpdateImageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableImageUpdateImageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageUpdateImageResponse(val *ImageUpdateImageResponse) *NullableImageUpdateImageResponse {
	return &NullableImageUpdateImageResponse{value: val, isSet: true}
}

func (v NullableImageUpdateImageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageUpdateImageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


