/*
API Образов облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVpsImage

import (
	"encoding/json"
)

// checks if the ImageRestoreImageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageRestoreImageRequest{}

// ImageRestoreImageRequest struct for ImageRestoreImageRequest
type ImageRestoreImageRequest struct {
	Id *string `json:"id,omitempty"`
	VpsId *string `json:"vps_id,omitempty"`
}

// NewImageRestoreImageRequest instantiates a new ImageRestoreImageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageRestoreImageRequest() *ImageRestoreImageRequest {
	this := ImageRestoreImageRequest{}
	return &this
}

// NewImageRestoreImageRequestWithDefaults instantiates a new ImageRestoreImageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageRestoreImageRequestWithDefaults() *ImageRestoreImageRequest {
	this := ImageRestoreImageRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ImageRestoreImageRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageRestoreImageRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ImageRestoreImageRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ImageRestoreImageRequest) SetId(v string) {
	o.Id = &v
}

// GetVpsId returns the VpsId field value if set, zero value otherwise.
func (o *ImageRestoreImageRequest) GetVpsId() string {
	if o == nil || IsNil(o.VpsId) {
		var ret string
		return ret
	}
	return *o.VpsId
}

// GetVpsIdOk returns a tuple with the VpsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageRestoreImageRequest) GetVpsIdOk() (*string, bool) {
	if o == nil || IsNil(o.VpsId) {
		return nil, false
	}
	return o.VpsId, true
}

// HasVpsId returns a boolean if a field has been set.
func (o *ImageRestoreImageRequest) HasVpsId() bool {
	if o != nil && !IsNil(o.VpsId) {
		return true
	}

	return false
}

// SetVpsId gets a reference to the given string and assigns it to the VpsId field.
func (o *ImageRestoreImageRequest) SetVpsId(v string) {
	o.VpsId = &v
}

func (o ImageRestoreImageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageRestoreImageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.VpsId) {
		toSerialize["vps_id"] = o.VpsId
	}
	return toSerialize, nil
}

type NullableImageRestoreImageRequest struct {
	value *ImageRestoreImageRequest
	isSet bool
}

func (v NullableImageRestoreImageRequest) Get() *ImageRestoreImageRequest {
	return v.value
}

func (v *NullableImageRestoreImageRequest) Set(val *ImageRestoreImageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableImageRestoreImageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableImageRestoreImageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageRestoreImageRequest(val *ImageRestoreImageRequest) *NullableImageRestoreImageRequest {
	return &NullableImageRestoreImageRequest{value: val, isSet: true}
}

func (v NullableImageRestoreImageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageRestoreImageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


