/*
API Образов облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVpsImage

import (
	"encoding/json"
)

// checks if the ImageCreateImageResponseError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageCreateImageResponseError{}

// ImageCreateImageResponseError struct for ImageCreateImageResponseError
type ImageCreateImageResponseError struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewImageCreateImageResponseError instantiates a new ImageCreateImageResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageCreateImageResponseError() *ImageCreateImageResponseError {
	this := ImageCreateImageResponseError{}
	return &this
}

// NewImageCreateImageResponseErrorWithDefaults instantiates a new ImageCreateImageResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageCreateImageResponseErrorWithDefaults() *ImageCreateImageResponseError {
	this := ImageCreateImageResponseError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ImageCreateImageResponseError) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageCreateImageResponseError) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ImageCreateImageResponseError) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ImageCreateImageResponseError) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ImageCreateImageResponseError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageCreateImageResponseError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ImageCreateImageResponseError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ImageCreateImageResponseError) SetMessage(v string) {
	o.Message = &v
}

func (o ImageCreateImageResponseError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageCreateImageResponseError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableImageCreateImageResponseError struct {
	value *ImageCreateImageResponseError
	isSet bool
}

func (v NullableImageCreateImageResponseError) Get() *ImageCreateImageResponseError {
	return v.value
}

func (v *NullableImageCreateImageResponseError) Set(val *ImageCreateImageResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableImageCreateImageResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableImageCreateImageResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageCreateImageResponseError(val *ImageCreateImageResponseError) *NullableImageCreateImageResponseError {
	return &NullableImageCreateImageResponseError{value: val, isSet: true}
}

func (v NullableImageCreateImageResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageCreateImageResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


