/*
API Образов облачных серверов

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1.0.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package begetOpenapiVpsImage

import (
	"encoding/json"
)

// checks if the ImageDeleteImageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageDeleteImageResponse{}

// ImageDeleteImageResponse struct for ImageDeleteImageResponse
type ImageDeleteImageResponse struct {
	Image *ImageImage `json:"image,omitempty"`
	Error *ImageDeleteImageResponseError `json:"error,omitempty"`
}

// NewImageDeleteImageResponse instantiates a new ImageDeleteImageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageDeleteImageResponse() *ImageDeleteImageResponse {
	this := ImageDeleteImageResponse{}
	return &this
}

// NewImageDeleteImageResponseWithDefaults instantiates a new ImageDeleteImageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageDeleteImageResponseWithDefaults() *ImageDeleteImageResponse {
	this := ImageDeleteImageResponse{}
	return &this
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *ImageDeleteImageResponse) GetImage() ImageImage {
	if o == nil || IsNil(o.Image) {
		var ret ImageImage
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageDeleteImageResponse) GetImageOk() (*ImageImage, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *ImageDeleteImageResponse) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given ImageImage and assigns it to the Image field.
func (o *ImageDeleteImageResponse) SetImage(v ImageImage) {
	o.Image = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ImageDeleteImageResponse) GetError() ImageDeleteImageResponseError {
	if o == nil || IsNil(o.Error) {
		var ret ImageDeleteImageResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageDeleteImageResponse) GetErrorOk() (*ImageDeleteImageResponseError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ImageDeleteImageResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given ImageDeleteImageResponseError and assigns it to the Error field.
func (o *ImageDeleteImageResponse) SetError(v ImageDeleteImageResponseError) {
	o.Error = &v
}

func (o ImageDeleteImageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageDeleteImageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableImageDeleteImageResponse struct {
	value *ImageDeleteImageResponse
	isSet bool
}

func (v NullableImageDeleteImageResponse) Get() *ImageDeleteImageResponse {
	return v.value
}

func (v *NullableImageDeleteImageResponse) Set(val *ImageDeleteImageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableImageDeleteImageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableImageDeleteImageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageDeleteImageResponse(val *ImageDeleteImageResponse) *NullableImageDeleteImageResponse {
	return &NullableImageDeleteImageResponse{value: val, isSet: true}
}

func (v NullableImageDeleteImageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageDeleteImageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


